#!/usr/bin/python3
#RSA Challenge

import sys

def factorize(number):
    factors = []
    for i in range(2, int(number**0.5) + 1):
        if number % i == 0:
            factors.append((i, number // i))
            return (factors)

        def main():
            if len(sys.argv) != 2:
                print("Usage: factors <file>")
                return

            filename = sys.argv[1]

            try:
                with open(filename, 'r') as file:
                    numbers = file.readlines()

                    for number in numbers:
                        number = int(number.strip())

                        factor_pairs = factorize(number)

                        for pair in factor_pairs:
                            print(f"{number} = {pair[0]} * {pair[1]}")
            except FileNotFoundError:
                print("File not found:", filename)

                if __name__ == "__main__":
                    main()
